// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPf587DkmhQuofRkNylDbivcVGABhM6xQ',
    appId: '1:1024725132776:web:4cb3c439084f8e3b6f305d',
    messagingSenderId: '1024725132776',
    projectId: 'murshed-dev',
    authDomain: 'murshed-dev.firebaseapp.com',
    storageBucket: 'murshed-dev.appspot.com',
    measurementId: 'G-10FRB5XXW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNRSYVBoY5NOK3Geth-wxfD2soLV4vYyg',
    appId: '1:1024725132776:android:cf323a5e638f31896f305d',
    messagingSenderId: '1024725132776',
    projectId: 'murshed-dev',
    storageBucket: 'murshed-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwkLLceTv7J5TcpRy0S5klcym_oZBmW0',
    appId: '1:1024725132776:ios:ed6b7f607d8576976f305d',
    messagingSenderId: '1024725132776',
    projectId: 'murshed-dev',
    storageBucket: 'murshed-dev.appspot.com',
    iosBundleId: 'com.murshed.sa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwkLLceTv7J5TcpRy0S5klcym_oZBmW0',
    appId: '1:1024725132776:ios:b159d6d4850baa716f305d',
    messagingSenderId: '1024725132776',
    projectId: 'murshed-dev',
    storageBucket: 'murshed-dev.appspot.com',
    iosBundleId: 'com.murshed.sa.murshed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPf587DkmhQuofRkNylDbivcVGABhM6xQ',
    appId: '1:1024725132776:web:6f3583ea9229195f6f305d',
    messagingSenderId: '1024725132776',
    projectId: 'murshed-dev',
    authDomain: 'murshed-dev.firebaseapp.com',
    storageBucket: 'murshed-dev.appspot.com',
    measurementId: 'G-2MYW78KKRY',
  );
}
